### ISSUE TITLE
Add floating point support

### ISSUE THREAD

**Issue by chsasank** [chsasank/llama.lisp#17]
Add floating point types

https://capra.cs.cornell.edu/bril/lang/float.html

and tests:

https://github.com/sampsyo/bril/tree/main/test/interp/float

Subset of #13

**Comment by GlowingScrewdriver** [comment]
LLVM supports ordered and unordered floating point operations. BRIL doesn't make a distinction between them.
Whether a comparison or ordered or not affects the outcome when one operand is `NaN`. I am not sure of the finer details.

Clang emits unordered comparison instructions when comparing arbitrary numbers. We will follow the same for now.

**Comment by GlowingScrewdriver** [comment]
Okay. Looks like the difference is this: if either operand is `NaN`, ordered operations return `false`, while unordered operations return `true`. So, makes sense to support the ordered operations.
