### ISSUE TITLE
sexp-json.scm does not recognize symbols `true` and `false`

### ISSUE THREAD

**Issue by GlowingScrewdriver** [chsasank/llama.lisp#27]
`sexp-json.scm` will convert Scheme's `#t` and `#f` to JSON's `true` and `false`, and does not recognize `true` and `false` in Scheme.

For example the following sexp:
```scheme
((const false)
 (const #f))
```
becomes the following JSON
```json
[["const", "false"],
 ["const", false]]
```
when passed through `sexp-json.scm`

Perhaps we should use `#t` and `#f` in the test .sexp files instead of `true` and `false`? The reason it hasn't been a problem so far is probably LLVMLite doing some internal handling of its own.

**Comment by chsasank** [comment]
Let's just use #t and #f in sexp just fine.
