### ISSUE TITLE
Prelisp: Preprocessor and Macros

### ISSUE THREAD

**Issue by GlowingScrewdriver** [chsasank/llama.lisp#32]
Macro functionality for our S-expression languages -- including Brilisp, C-Lisp and future layers -- is desirable. Using Scheme as the preprocessor will make the implementation straightforward, as well as give the programmer a powerful language to work with.
Whereas C macros are based on simple text substitution, our macro system will allow actual computations in the macro output.

The idea is that every macro is a Scheme procedure, and a macro reference is replaced with the result of a call to the corresponding procedure. There will be one keyword to indicate that an expression in the program is a macro reference. The syntax will be inspired by Scheme's `let`, something like:
```scheme
(prelisp
   ( ; Macro definitions
      (add5  (lambda (x) (+ x 5)))
   )

   (c-lisp ; Program
      (define ((main void))
         (call print (eval-macro (add5 3)))
         (ret)))
```
This will be processed to:
```scheme
   (c-lisp ; Program
      (define ((main void))
         (call print 8)
         (ret)))
```
And this will be passed to the compiler (C-Lisp in this case). Notice how `(eval-macro (add5 3))` wasn't just substituted with `(+ 5 3)`; `(+ 5 3)` was actually evaluated as `8` by the scheme interpreter before being substituted back

**Comment by chsasank** [comment]
Implemented by #83
