### ISSUE TITLE
The instruction "declare" is counter intuitive when compared to most other instructions.

### ISSUE THREAD

**Issue by adi-lb-phoenix** [chsasank/llama.lisp#55]
We have the instruction ``` (set a 10)```,  ``` (add a b)``` ```(fmul a b)```.  But the instruction declare is defined as ```(declare (a int))``` . Why do we require an additional ```()``` after ```declare```. It does not add any features and is counter intuitive. Instead I propose a change in syntax which is intuitive and simple  ```(declare a int)```

**Comment by GlowingScrewdriver** [comment]
I agree with this. There is no solid reason for having parenthesis around the variable name and type, since there are no optional/variable-length components in a `declare` statement.

@chsasank What do you think?
