### ISSUE TITLE
Casting from int to float and float to int

### ISSUE THREAD

**Issue by adi-lb-phoenix** [chsasank/llama.lisp#67]
We should be able to cast floating point values from integer values . We do not have equivalent C code and its LLVM IR issue.
for ex : 
```
(declare a int)
(set a 10)
(declare b float)
(set b 10.0)
(declare c float)
(set c (fadd a b ))
```
We cannot add 'a' and 'b' as both of them are in different formats. We should be able to change the format of 'a' to float before adding it.

We should be able to do something similar to the below : 

```
(c-lisp

    (define ((fprint float) (n  float) ))

    (define ((main void))
    (declare a int)
    (declare b float)
    (declare c float)
    (set a 10)
    (set b 10.0)
    (declare a float)
    (set c (fadd a b))
    (call fprint c)

    )
)
```
The output when the above is executed executed : 

```
guile ../../utils/sexp-json.scm < test.sexp  | python ../../c-lisp.py | python ../../brilisp.py | python ../../llvm.py | bash ../brilisp/run.sh {args}
Error in statement: ['declare', 'a', 'float']
Traceback (most recent call last):
  File "/home/aadithya.bhat/c_lisp/bril/bril-txt/llama.lisp/src/backend/tests/c-lisp/../../c-lisp.py", line 473, in <module>
    json.dump(brilisp_code_generator.c_lisp(json.loads(sys.stdin.read())), sys.stdout)
  File "/home/aadithya.bhat/c_lisp/bril/bril-txt/llama.lisp/src/backend/tests/c-lisp/../../c-lisp.py", line 59, in c_lisp
    return ["brilisp"] + [self.gen_function(fn) for fn in prog[1:]]
  File "/home/aadithya.bhat/c_lisp/bril/bril-txt/llama.lisp/src/backend/tests/c-lisp/../../c-lisp.py", line 59, in <listcomp>
    return ["brilisp"] + [self.gen_function(fn) for fn in prog[1:]]
  File "/home/aadithya.bhat/c_lisp/bril/bril-txt/llama.lisp/src/backend/tests/c-lisp/../../c-lisp.py", line 125, in gen_function
    *self.gen_compound_stmt(
  File "/home/aadithya.bhat/c_lisp/bril/bril-txt/llama.lisp/src/backend/tests/c-lisp/../../c-lisp.py", line 303, in gen_compound_stmt
    instr_list += self.gen_stmt(s)
  File "/home/aadithya.bhat/c_lisp/bril/bril-txt/llama.lisp/src/backend/tests/c-lisp/../../c-lisp.py", line 163, in gen_stmt
    raise e
  File "/home/aadithya.bhat/c_lisp/bril/bril-txt/llama.lisp/src/backend/tests/c-lisp/../../c-lisp.py", line 150, in gen_stmt
    return self.gen_decl_stmt(stmt)
  File "/home/aadithya.bhat/c_lisp/bril/bril-txt/llama.lisp/src/backend/tests/c-lisp/../../c-lisp.py", line 271, in gen_decl_stmt
    raise CodegenError(f"Re-declaration of variable {name}")
__main__.CodegenError: Re-declaration of variable a
Traceback (most recent call last):
  File "/home/aadithya.bhat/c_lisp/bril/bril-txt/llama.lisp/src/backend/tests/c-lisp/../../brilisp.py", line 174, in <module>
    main()
  File "/home/aadithya.bhat/c_lisp/bril/bril-txt/llama.lisp/src/backend/tests/c-lisp/../../brilisp.py", line 169, in main
    expr = json.load(sys.stdin)
  File "/gnu/store/kgxbvcr9ks2k8lbm8fla7zvp63dbagrc-python-3.10.7/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/gnu/store/kgxbvcr9ks2k8lbm8fla7zvp63dbagrc-python-3.10.7/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/gnu/store/kgxbvcr9ks2k8lbm8fla7zvp63dbagrc-python-3.10.7/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/gnu/store/kgxbvcr9ks2k8lbm8fla7zvp63dbagrc-python-3.10.7/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/home/aadithya.bhat/c_lisp/bril/bril-txt/llama.lisp/src/backend/tests/c-lisp/../../llvm.py", line 359, in <module>
    main()
  File "/home/aadithya.bhat/c_lisp/bril/bril-txt/llama.lisp/src/backend/tests/c-lisp/../../llvm.py", line 352, in main
    bril_prog = munch.munchify(json.load(sys.stdin))
  File "/gnu/store/kgxbvcr9ks2k8lbm8fla7zvp63dbagrc-python-3.10.7/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/gnu/store/kgxbvcr9ks2k8lbm8fla7zvp63dbagrc-python-3.10.7/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/gnu/store/kgxbvcr9ks2k8lbm8fla7zvp63dbagrc-python-3.10.7/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/gnu/store/kgxbvcr9ks2k8lbm8fla7zvp63dbagrc-python-3.10.7/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
/usr/bin/ld: /gnu/store/ln6hxqjvz6m9gdd9s97pivlqck7hzs99-glibc-2.35/lib/Scrt1.o: in function `_start':
(.text+0x17): undefined reference to `main'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
../brilisp/run.sh: line 9: /tmp/tmp.InjTJQHqDK.out: No such file or directory
rm: cannot remove '/tmp/tmp.InjTJQHqDK.out': No such file or directory
```

**Comment by chsasank** [comment]
Can you write some C code and show generated LLVM IR with clang?

LLVM has many casting ops, we need to decide on which ones to implement: https://llvm.org/docs/LangRef.html#conversion-operations

**Comment by GlowingScrewdriver** [comment]
> We should be able to do something similar to the below :
```
    (define ((main void))
    (declare a int)
    (declare b float)
    (declare c float)
    (set a 10)
    (set b 10.0)
    (declare a float)
    (set c (fadd a b))
    (call fprint c)
```

I don't think this should be the syntax. Semantically, `a` is redeclared so that it is used as a float instead of an int.

I think we should implement casting as an operator, like how C does it. So in this example, `a` should not be modified, and the result of the casting expression will be a new floating-point value.

Explicit casts in C work like this:
```C
int val;
val = 10; // val is integer 10
float fval;
fval = (float) val; // fval is float 10, and val is still integer 10
```

Following the same pattern in C-Lisp, we would end up with something like:
```scheme
(declare val int)
(set val 10) ; val is integer 10
(declare fval float)
(set fval (sitofp val)) ; fval is float 10, and fval is still integer 10
```
`sitofp` (or whatever name we decide on) would be the casting operator.

**Comment by adi-lb-phoenix** [comment]
I agree with your point, we should not redeclare it, rather use it as a casting operator. Regarding naming conventions. I do not think it best to use any keywords that are implemented in any other language, as I believe it might lead to issues while debugging. Although C-lisp and llvm.py are apart by one compiler (brilisp.py).

**Comment by adi-lb-phoenix** [comment]
> ```
> (c-lisp
> 
>     (define ((fprint float) (n  float) ))
> 
>     (define ((main void))
>     (declare a int)
>     (declare b float)
>     (declare c float)
>     (set a 10)
>     (set b 10.0)
>     (declare a float)
>     (set c (fadd a b))
>     (call fprint c)
> 
>     )
> )
```
The error occurred when it was passed to llvm.py
command : guile ../../utils/sexp-json.scm < test.sexp | python ../../c-lisp.py | python ../../brilisp.py | python ../../llvm.py

**Comment by adi-lb-phoenix** [comment]
How did the function traversal happen : 
`main()`-> `code_gen.generate(bril_prog)` -> ` self.gen_function(fn)` -> `self.gen_instructions(fn_instrs)`-> `  self.gen_instructions(fn_instrs)` -> ` raise e` in `gen_instructions`  -> gen_value(instr) in `gen_instructions` ->

check the below line in the code : 
line 163, in gen_value
    llvm_instr(*[self.gen_var(arg) for arg in instr.args], name=instr.dest),
  File "home/.local/lib/python3.10/site-packages/llvmlite/ir/builder.py", line 34, in wrapped
    raise ValueError("Operands must be the same type, got (%s, %s)"

**Comment by adi-lb-phoenix** [comment]
On inspecting `gen_value` function. The error seems to be returning from `llvm_instr(*[self.gen_var(arg) for arg in instr.args], name=instr.dest)`. 
I printed the contents of the list fed into `llvm_instr()` function.
`
 print([self.gen_var(arg) for arg in instr.args] ,"REPL")
 `
 Contents : 
 ```
 [<ir.LoadInstr '.12' of type 'i32', opname 'load', operands [<ir.AllocaInstr 'tmp_clisp.inp_0-gjhylhwu' of type 'i32*', opname 'alloca', operands ()>]>, <ir.LoadInstr '.13' of type 'float', opname 'load', operands [<ir.AllocaInstr 'tmp_clisp.inp_1-ffnjzeqi' of type 'float*', opname 'alloca', operands ()>]>] REPL
 ```
 REPL is just to recognize the printed contents

**Comment by adi-lb-phoenix** [comment]
Above 3 comments are to be ignored for now.

**Comment by adi-lb-phoenix** [comment]
`
(c-lisp

    (define ((fprint float) (n  float) ))

    (define ((main void))
        (declare a int)
        (declare b float)
        (declare c float)
        (set a 10)
        (set b 10.0)
        (declare a float)
        (set c (fadd a b))
        (call fprint c)

    )

)Error in statement: ['declare', 'a', 'float']
Traceback (most recent call last):
  File "/home/aadithya.bhat/c_lisp/bril/bril-txt/llama.lisp/src/backend/tests/c-lisp/llama2.c/int_to_float/../../../../c-lisp.py", line 473, in <module>
    json.dump(brilisp_code_generator.c_lisp(json.loads(sys.stdin.read())), sys.stdout)
  File "/home/aadithya.bhat/c_lisp/bril/bril-txt/llama.lisp/src/backend/tests/c-lisp/llama2.c/int_to_float/../../../../c-lisp.py", line 59, in c_lisp
    return ["brilisp"] + [self.gen_function(fn) for fn in prog[1:]]
  File "/home/aadithya.bhat/c_lisp/bril/bril-txt/llama.lisp/src/backend/tests/c-lisp/llama2.c/int_to_float/../../../../c-lisp.py", line 59, in <listcomp>
    return ["brilisp"] + [self.gen_function(fn) for fn in prog[1:]]
  File "/home/aadithya.bhat/c_lisp/bril/bril-txt/llama.lisp/src/backend/tests/c-lisp/llama2.c/int_to_float/../../../../c-lisp.py", line 125, in gen_function
    *self.gen_compound_stmt(
  File "/home/aadithya.bhat/c_lisp/bril/bril-txt/llama.lisp/src/backend/tests/c-lisp/llama2.c/int_to_float/../../../../c-lisp.py", line 303, in gen_compound_stmt
    instr_list += self.gen_stmt(s)
  File "/home/aadithya.bhat/c_lisp/bril/bril-txt/llama.lisp/src/backend/tests/c-lisp/llama2.c/int_to_float/../../../../c-lisp.py", line 163, in gen_stmt
    raise e
  File "/home/aadithya.bhat/c_lisp/bril/bril-txt/llama.lisp/src/backend/tests/c-lisp/llama2.c/int_to_float/../../../../c-lisp.py", line 150, in gen_stmt
    return self.gen_decl_stmt(stmt)
  File "/home/aadithya.bhat/c_lisp/bril/bril-txt/llama.lisp/src/backend/tests/c-lisp/llama2.c/int_to_float/../../../../c-lisp.py", line 271, in gen_decl_stmt
    raise CodegenError(f"Re-declaration of variable {name}")
__main__.CodegenError: Re-declaration of variable a
`

**Comment by adi-lb-phoenix** [comment]
(c-lisp

    (define ((fprint float) (n  float) ))

    (define ((main void))
        (declare a int)
        (declare b float)
        (declare c float)
        (set a 10)
        (set b 10.0)
        (sitofp a)
        (set c (fadd a b))
        (call fprint c)

    )
`

exp-json.scm < test.sexp | python ../../../../c-lisp.py 
Error in statement: ['sitofp', 'a']
Traceback (most recent call last):
  File "/home/aadithya.bhat/c_lisp/bril/bril-txt/llama.lisp/src/backend/tests/c-lisp/llama2.c/int_to_float/../../../../c-lisp.py", line 473, in <module>
    json.dump(brilisp_code_generator.c_lisp(json.loads(sys.stdin.read())), sys.stdout)
  File "/home/aadithya.bhat/c_lisp/bril/bril-txt/llama.lisp/src/backend/tests/c-lisp/llama2.c/int_to_float/../../../../c-lisp.py", line 59, in c_lisp
    return ["brilisp"] + [self.gen_function(fn) for fn in prog[1:]]
  File "/home/aadithya.bhat/c_lisp/bril/bril-txt/llama.lisp/src/backend/tests/c-lisp/llama2.c/int_to_float/../../../../c-lisp.py", line 59, in <listcomp>
    return ["brilisp"] + [self.gen_function(fn) for fn in prog[1:]]
  File "/home/aadithya.bhat/c_lisp/bril/bril-txt/llama.lisp/src/backend/tests/c-lisp/llama2.c/int_to_float/../../../../c-lisp.py", line 125, in gen_function
    *self.gen_compound_stmt(
  File "/home/aadithya.bhat/c_lisp/bril/bril-txt/llama.lisp/src/backend/tests/c-lisp/llama2.c/int_to_float/../../../../c-lisp.py", line 303, in gen_compound_stmt
    instr_list += self.gen_stmt(s)
  File "/home/aadithya.bhat/c_lisp/bril/bril-txt/llama.lisp/src/backend/tests/c-lisp/llama2.c/int_to_float/../../../../c-lisp.py", line 163, in gen_stmt
    raise e
  File "/home/aadithya.bhat/c_lisp/bril/bril-txt/llama.lisp/src/backend/tests/c-lisp/llama2.c/int_to_float/../../../../c-lisp.py", line 158, in gen_stmt
    return self.gen_expr(stmt)
  File "/home/aadithya.bhat/c_lisp/bril/bril-txt/llama.lisp/src/backend/tests/c-lisp/llama2.c/int_to_float/../../../../c-lisp.py", line 468, in gen_expr
    raise CodegenError(f"Bad expression: {expr}")
__main__.CodegenError: Bad expression: ['sitofp', 'a']
`

**Comment by adi-lb-phoenix** [comment]
We will not try to solve this in C-lisp first, but we will do it from brilisp first. 

```
(brilisp 
    (define ((print int) (n int)))

    (define ((add5 float) (n int))
        (set (five float) (const 5.0))
        (sitofp n)
        (set (sum float) (add n five))
        (ret sum)
    )

    (define (( main float)) 
        (set (a int) (const 9))
        (set (b int) (call add5 a))
        (set (tmp int)(call print b))
        (ret b)

    )
```
command executed : ` guile ../../../utils/sexp-json.scm < I_2_F.sexp | python ../../../brilisp_1.py`
Output : 
``` 
Traceback (most recent call last):
  File "/home/aadithya.bhat/c_lisp/bril/bril-txt/llama.lisp/src/backend/tests/brilisp/int_to_float/../../../brilisp_1.py", line 174, in <module>
    main()
  File "/home/aadithya.bhat/c_lisp/bril/bril-txt/llama.lisp/src/backend/tests/brilisp/int_to_float/../../../brilisp_1.py", line 170, in main
    print(json.dumps(brilisp(expr)))
  File "/home/aadithya.bhat/c_lisp/bril/bril-txt/llama.lisp/src/backend/tests/brilisp/int_to_float/../../../brilisp_1.py", line 165, in brilisp
    return {"functions": [gen_function(x) for x in body]}
  File "/home/aadithya.bhat/c_lisp/bril/bril-txt/llama.lisp/src/backend/tests/brilisp/int_to_float/../../../brilisp_1.py", line 165, in <listcomp>
    return {"functions": [gen_function(x) for x in body]}
  File "/home/aadithya.bhat/c_lisp/bril/bril-txt/llama.lisp/src/backend/tests/brilisp/int_to_float/../../../brilisp_1.py", line 23, in gen_function
    "instrs": [gen_instr(x) for x in instrs],
  File "/home/aadithya.bhat/c_lisp/bril/bril-txt/llama.lisp/src/backend/tests/brilisp/int_to_float/../../../brilisp_1.py", line 23, in <listcomp>
    "instrs": [gen_instr(x) for x in instrs],
  File "/home/aadithya.bhat/c_lisp/bril/bril-txt/llama.lisp/src/backend/tests/brilisp/int_to_float/../../../brilisp_1.py", line 157, in gen_instr
    raise SyntaxError(f"Unknown instruction {instr}")
SyntaxError: Unknown instruction ['sitofp', 'n']
```

**Comment by GlowingScrewdriver** [comment]
Here is how I'd go about implementing cast in Brilisp:
* Create a new operator in Brilisp. Call it by the same name as LLVM's int-to-float cast: `sitofp`. In terms of the Brilisp compiler architecture, this will be defined alongside other operations like the arithmetic, pointer, etc.
* LLVM `sitofp` takes the result type as an argument (the result is a floating-point, but the argument specifies precision -- `float`/`double`). For now, we will hardcode that argument since we have only one floating-point type.
* Do not insert implicit casts anywhere. That is a conscious design decision adopted in both Brilisp and C-Lisp. If a cast is needed, the programmer will write one.

Some operations you can look at for reference:
* `id`: Possibly the simplest instruction.
* Any "value" instruction, like `add`: Direct mapping to LLVM instructions.

**Comment by adi-lb-phoenix** [comment]
Defined the below functions in `gen_instr(instr):` of brilisp_1.py. brilisp_1py is a copy of brilisp.py.

```
def is_sitofp(instr):
        return instr[0] == "sitofp"
    
    def gen_sitofp_instr(instr):
        return {"op":"sitofp", "args": instr[1]}
    
    def is_fptosi(instr):
        return instr[0] == "fptosi"
    
    def gen_fptos_instr(instr):
        return {"op":"fptosi", "args": instr[1]}
```
Why did I do it ? 
I observed that in this function, each instruction was being checked if the 0th position of that list matched a instruction name and if true a a new function in the name of "gen_instructionNAME_instr" was created to generate instructions in brilisp format.
Next step is to observe the functions calling functions such as above and add conditions/statements in the calling function that lets the above defined functions to generate instructions when instructions such as "sitofp" and "fitosi" is encoured.

**Comment by adi-lb-phoenix** [comment]
@GlowingScrewdriver 
> Here is how I'd go about implementing cast in Brilisp:
> 
>     * Create a new operator in Brilisp. Call it by the same name as LLVM's int-to-float cast: `sitofp`. In terms of the Brilisp compiler architecture, this will be defined alongside other operations like the arithmetic, pointer, etc.
> 
>     * LLVM `sitofp` takes the result type as an argument (the result is a floating-point, but the argument specifies precision -- `float`/`double`). For now, we will hardcode that argument since we have only one floating-point type.
> 
>     * Do not insert implicit casts anywhere. That is a conscious design decision adopted in both Brilisp and C-Lisp. If a cast is needed, the programmer will write one.
> 
> 
> Some operations you can look at for reference:
> 
>     * `id`: Possibly the simplest instruction.
> 
>     * Any "value" instruction, like `add`: Direct mapping to LLVM instructions.

I have taken your valuable suggestions and the directions into account 💯 👍

**Comment by adi-lb-phoenix** [comment]
I have added the below lines of code : 
```
elif is_sitofp(instr):
            return gen_sitofp_instr(instr)
    elif is_fptosi(instr):
            return (gen_fptosi_instr)
```
along with these : 
```
if is_const(instr):
        return gen_constr_instr(instr)
    elif is_value(instr):
        return gen_value_instr(instr)
    elif is_ret(instr):
        return gen_ret_instr(instr)
    elif is_call(instr):
        return gen_call_instr(instr)
    elif is_jmp(instr):
        return gen_jmp_instr(instr)
    elif is_label(instr):
        return gen_label_instr(instr)
    elif is_br(instr):
        return gen_br_instr(instr)
    elif is_nop(instr):
        return gen_nop_instr(instr)
    elif is_store(instr):
        return gen_store_instr(instr)
    elif is_sitofp(instr):
            return gen_sitofp_instr(instr)
    elif is_fptosi(instr):
            return (gen_fptosi_instr)
    else:
        raise SyntaxError(f"Unknown instruction {instr}")
```

All the above code is present in `gen_instr(instr)` function

**Comment by adi-lb-phoenix** [comment]
Executed the below program 
```
(brilisp 
    (define ((print int) (n int)))

    (define ((add5 float) (n int))
        (set (five float) (const 5.0))
        (sitofp n)
        (set (sum float) (add n five))
        (ret sum)
    )

    (define (( main float)) 
        (set (a int) (const 9))
        (set (b float) (call add5 a))
        (set (tmp int)(call print b))
        (ret b)
    )

```
Output when excuted command `guile ../../../utils/sexp-json.scm < I_2_F.sexp | python ../../../brilisp_1.py`. 
Output  : 
`
{"functions": [{"name": "print", "type": "int", "args": [{"name": "n", "type": "int"}], "instrs": []}, {"name": "add5", "type": "float", "args": [{"name": "n", "type": "int"}], "instrs": [{"op": "const", "type": "float", "dest": "five", "value": 5.0}, {"op": "sitofp", "args": "n"}, {"op": "add", "type": "float", "dest": "sum", "args": ["n", "five"]}, {"op": "ret", "args": ["sum"]}]}, {"name": "main", "type": "float", "args": [], "instrs": [{"op": "const", "type": "int", "dest": "a", "value": 9}, {"op": "call", "type": "float", "dest": "b", "funcs": ["add5"], "args": ["a"]}, {"op": "call", "type": "int", "dest": "tmp", "funcs": ["print"], "args": ["b"]}, {"op": "ret", "args": ["b"]}]}]}
`

**Comment by GlowingScrewdriver** [comment]
We don't want to change the original variable while performing a cast. The cast operator takes an integer as an operand, and produces a _new_ floating-point value. So `add5` in your program should look something like:
```
    (define ((add5 float) (n int))
        (set (five float) (const 5.0))
        (set (f_n float) (sitofp n))
        (set (sum float) (add f_n five))
        (ret sum)
    )
```

**Comment by adi-lb-phoenix** [comment]
Why don't you want to change the original variable ? is it To maintain scope ?

**Comment by GlowingScrewdriver** [comment]
Because that's not how casts work in LLVM, (or C, for that matter). And we are saving ourselves much of the trouble of language design by adopting the semantics of LLVM and C.

**Comment by GlowingScrewdriver** [comment]
Thing is, we can't think of all the caveats of a design decision when we make it. But the C language has been around for decades, _and_ has undergone many improvements. LLVM too is quite mature. So following their footsteps definitely can't go wrong.

**Comment by adi-lb-phoenix** [comment]
```
(brilisp 
    (define ((print int) (n int)))

    (define ((add5 float) (n int))
        (set (five float) (const 5.0))
        (set (f_n float) (sitofp n))
        (set (sum float) (add n five))
        (ret sum)
    )

    (define (( main float)) 
        (set (a int) (const 9))
        (set (b float) (call add5 a))
        (set (tmp int)(call print b))
        (ret b)
    )
)
```
In brilisp_1.py . 
```
    def is_value(instr):
        value_op = {
            "add",
            "mul",
            "sub",
            "div",
            "eq",
            "ne",
            "lt",
            "gt",
            "le",
            "ge",
            "not",
            "and",
            "or",
            "alloc",
            "load",
            "ptradd",
            "id",
            "fadd",
            "fsub",
            "fmul",
            "fdiv",
            "feq",
            "fne",
            "flt",
            "fgt",
            "fle",
            "fge",
            "sitofp",
            "fptosi"
        }
```
made Changes to the function defined  [https://github.com/chsasank/llama.lisp/issues/67#issuecomment-2211671406] as below 
```
    def is_sitofp(instr):
        print(instr,"REPL")
        if instr[1][1] not in ["float"]:
            raise TypeError("type does not match float")
        return instr[0] == "sitofp"
    
    def gen_sitofp_instr(instr):
        return {"op":"sitofp","type":instr[1][1],"args": instr[1][0]}
    
    def is_fptosi(instr):
        print(instr,"REPL")
        if instr[1][1] not in ["int"]:
            raise TypeError("type does not match int")
        return instr[0] == "fptosi"
    
    def gen_fptosi_instr(instr):
        return {"op":"fptosi", "type":instr[1][1], "args": instr[1][0]}
```
```
guile ../../../utils/sexp-json.scm < I_2_F.sexp | python ../../../brilisp_1.py 
{"functions": [{"name": "print", "type": "int", "args": [{"name": "n", "type": "int"}], "instrs": []}, {"name": "add5", "type": "float", "args": [{"name": "n", "type": "int"}], "instrs": [{"op": "const", "type": "float", "dest": "five", "value": 5.0}, {"op": "sitofp", "type": "float", "dest": "f_n", "args": ["n"]}, {"op": "add", "type": "float", "dest": "sum", "args": ["n", "five"]}, {"op": "ret", "args": ["sum"]}]}, {"name": "main", "type": "float", "args": [], "instrs": [{"op": "const", "type": "int", "dest": "a", "value": 9}, {"op": "call", "type": "float", "dest": "b", "funcs": ["add5"], "args": ["a"]}, {"op": "call", "type": "int", "dest": "tmp", "funcs": ["print"], "args": ["b"]}, {"op": "ret", "args": ["b"]}]}]}
```

 {"op": "sitofp", "type": "float", "dest": "f_n", "args": ["n"]} . With this approach I don't

**Comment by adi-lb-phoenix** [comment]
in llvm.py , the function which will build the IR for sitofp : 
```
def gen_sitofp(instr):
            # IRBuilder.sitofp(value, typ, name='')
            self.declare_var(self.gen_type(instr.type), instr.dest)
            self.gen_symbol_store(instr.dest,
                self.builder.sitofp(
                    self.gen_var(instr.args[0]),self.gen_type(instr.type),name=self.gen_var(instr.dest))
```

**Comment by adi-lb-phoenix** [comment]
> in llvm.py , the function which will build the IR for sitofp :
> 
> ```
> def gen_sitofp(instr):
>             # IRBuilder.sitofp(value, typ, name='')
>             self.declare_var(self.gen_type(instr.type), instr.dest)
>             self.gen_symbol_store(instr.dest,
>                 self.builder.sitofp(
>                     self.gen_var(instr.args[0]),self.gen_type(instr.type),name=self.gen_var(instr.dest))
> ```
> 
> Command : `guile ../../../utils/sexp-json.scm < I_2_F.sexp | python ../../../brilisp_1.py | python ../../../llvm.py `
`
Updated an instruction in `gen_sitofp` function : 
`self.gen_var(instr.args[0]),self.gen_type(instr.type),name=instr.dest` 
Output : 
```
%".5" = load float, float* %"f_n" REPL
; ModuleID = ""
target triple = "unknown-unknown-unknown"
target datalayout = ""

declare float @"fprint"(float %".1")

define float @"add5"(i32 %"n")
{
alloca-bncsohpf:
  %"n.1" = alloca i32
  %"five" = alloca float
  %"f_n" = alloca float
  %"sum" = alloca float
  br label %"entry-toewuyga"
entry-toewuyga:
  store i32 %"n", i32* %"n.1"
  store float 0x4014000000000000, float* %"five"
  %".5" = load float, float* %"f_n"
  %".6" = load i32, i32* %"n.1"
  %"f_n.1" = sitofp i32 %".6" to float
  store float %"f_n.1", float* %"f_n"
  %".8" = load float, float* %"f_n"
  %".9" = load float, float* %"five"
  %"sum.1" = fadd float %".8", %".9"
  store float %"sum.1", float* %"sum"
  %".11" = load float, float* %"sum"
  ret float %".11"
}

define float @"main"()
{
alloca-npgxravk:
  %"a" = alloca i32
  %"b" = alloca float
  %"tmp" = alloca float
  br label %"entry-yuytbslm"
entry-yuytbslm:
  store i32 9, i32* %"a"
  %".3" = load i32, i32* %"a"
  %"b.1" = call float @"add5"(i32 %".3")
  store float %"b.1", float* %"b"
  %".5" = load float, float* %"b"
  %"tmp.1" = call float @"fprint"(float %".5")
  store float %"tmp.1", float* %"tmp"
  %".7" = load float, float* %"b"
  ret float %".7"
}
```

**Comment by adi-lb-phoenix** [comment]
Brilisp file : 
```
(brilisp 
    (define ((fprint float) (n float)))

    (define ((add5 float) (n int))
        (set (five float) (const 5.0))
        (set (f_n float) (sitofp n))
        (set (sum float) (fadd f_n five))
        (ret sum)
    )

    (define (( main float)) 
        (set (a int) (const 9))
        (set (b float) (call add5 a))
        (set (tmp float) (call fprint b))
        (ret b)
    )


)
```
Command : 
`guile ../../../utils/sexp-json.scm < I_2_F.sexp | python ../../../brilisp_1.py | python ../../../llvm.py | bash ../run.sh `

Output : 
```
14.000000

```

**Comment by adi-lb-phoenix** [comment]
For float to int in brilisp.py we had already added the functions `is_fptosi(instr)` and `gen_fptosi_instr(instr)` which would verify and generate the required library for us.

in llvm.py 

We add the below function in `gen_instructions`
 ```
 def gen_fptosi(instr):
            self.declare_var(self.gen_type(instr.type), instr.dest)
            self.gen_symbol_store(instr.dest,
                    self.builder.fptosi(
                        self.gen_var(instr.args[0]),self.gen_type(instr.type),name=instr.dest
                                        )
                                )
```
And the below lines of code 
```
elif instr.op == "sitofp":
                    gen_sitofp(instr)
                elif instr.op =="fptosi":
                    gen_fptosi(instr)
```
in `gen_instructions(self, instrs):` 

The below brilisp code does conversion from float to int and performs addition operation on int and a value which has been converted from float to int.
```
(brilisp 
    (define ((print int) (n int)))

    (define ((add5 int) (n float))
        (set (five int) (const 5))
        (set (f_n int) (fptosi n))
        (set (sum int) (add f_n five))
        (ret sum)
    )

    (define (( main int)) 
        (set (a float) (const 9.0))
        (set (b int) (call add5 a))
        (set (tmp int) (call print b))
        (ret b)
    )


)
```
Command : `guile ../../../utils/sexp-json.scm < F_2_I.sexp | python ../../../brilisp.py | python ../../../llvm.py | bash ../run.sh `

Output : 
```
14
```

**Comment by GlowingScrewdriver** [comment]
Don't use this issue to post progress on the code. That's what you should use a PR for.
