### ISSUE TITLE
Add more tests from BRIL

### ISSUE THREAD

**Issue by chsasank** [chsasank/llama.lisp#9]
Port the tests from bril repo to BRILISP and add it to tests. Ensure they pass. Add features if they are missing.

Find the tests here:

https://github.com/sampsyo/bril/tree/main/test/interp/core

Not all will be valid for us. Port what we can.

**Comment by GlowingScrewdriver** [comment]
This is done right?

**Comment by chsasank** [comment]
Yep. #11 fixed tests for core.
